import SwiftUI

@ViewBuilder
func appDestination(for entry: AppEntry) -> some View {
    switch entry.name {
    case "Color":                  ColorReferenceView()
    case "Typography":             TypographyReferenceView()
    case "Text Layout Anatomy":    TextLayoutAnatomyView()
    case "Paragraph & Line Control": ParagraphLineControlView()
    case "Spacing & Layout":       SpacingView()
    case "Buttons":                ButtonsView()
    case "Menus & Context Menus":  MenusView()
    case "Menu Studio":            MenuStudioView()
    case "Text Fields":            TextFieldsView()
    case "Rich Text Editor":       RichTextEditorView()
    case "Toggles & Switches":     TogglesView()
    case "Sliders":                SlidersView()
    case "Steppers":               SteppersView()
    case "Pickers":                PickersView()
    case "Segmented Controls":     SegmentedControlsView()
    case "Date & Time Pickers":    DateTimePickersView()
    case "Color Picker":           ColorPickerView()
    case "Images & Icons":         ImagesView()
    case "Progress Indicators":    ProgressIndicatorsView()
    case "Gauges":                 GaugesView()
    case "Badges":                 BadgesView()
    case "Tags":                   TagsView()
    case "Lists & Tables":         ListsView()
    case "Swipeable Rows":         SwipeableRowsView()
    case "Scroll Views":           ScrollViewsView()
    case "Lazy Stacks":            LazyStacksView()
    case "Carousels":              CarouselsView()
    case "Grids":                  GridsView()
    case "Grouped Forms":          GroupedFormsView()
    case "Cards":                  CardsView()
    case "Navigation Bars & Toolbars": NavigationBarsAndToolbarsView()
    case "Tab Bars":               TabBarsView()
    case "Search":                 SearchComponentView()
    case "Sheets & Modals":        SheetsModalsView()
    case "Alerts & Dialogs":       AlertsView()
    case "Action Sheets":          ActionSheetsView()
    case "Popovers":               PopoversView()
    case "Toasts & Banners":       ToastsView()
    case "Navigation Patterns":    NavigationPatternsView()
    case "Tab Bar Patterns":       TabPatternView()
    case "Tab Bar → Toolbar":      TabBarToolbarTransitionView()
    case "Modal Patterns":         ModalPatternsView()
    case "Form Patterns":          FormPatternView()
    case "Empty States":           EmptyStatesView()
    case "Loading States":         LoadingStatesView()
    case "Reorderable List":       ReorderableListView()
    case "Error States":           ErrorStatesView()
    case "Settings Patterns":      SettingsPatternView()
    case "Onboarding Flows":       OnboardingView()
    case "iOS 26 Glass":           GlassEffectPlayground()
    case "Material (blur)":        GlassPlayground()
    case "Surfaces":               SurfacesPlayground()
    case "Vibrancy":               VibrancyPlayground()
    case "Shaders":                ShadersPlaygroundView()
    case "Spring Physics":         SpringPhysicsView()
    case "Corner Radius":          CornerRadiusView()
    case "Concentric Radius":      ConcentricRadiusView()
    case "Shadow Explorer":        ShadowExplorerView()
    case "Blur Stack":             BlurStackView()
    case "Mesh Gradient":          MeshGradientPlaygroundView()
    case "Fluid Gradient":         FluidGradientView()
    case "Random Metaball 2D":     RandomMetaball2DView()
    case "Circle SDF 1":           CircleSDF1View()
    case "Circle SDF 2":           CircleSDF2View()
    case "Smooth Min 2D":          SmoothMin2DView()
    case "Implicit Equation":      ImplicitEquationView()
    case "Lissajous Curve":        LissajousCurveView()
    case "Radial Layout":          RadialLayoutView()
    case "Flow Layout":            FlowLayoutView()
    case "Flow Distortion":        FlowDistortionView()
    case "Physics Tag":            PhysicsTagView()
    case "Soft Body":              SoftBodyView()
    case "Stable Fluid":           StableFluidView()
    case "Liquid Wallet":          LiquidWalletView()
    case "Liquid Carousel":        LiquidCarouselView()
    case "Glass Morph":            GlassMorphView()
    case "Sheet Detent Morph":     SheetDetentMorphView()
    case "Tab Mini Player":        TabBarMiniPlayerView()
    case "Toolbar Condense":       ToolbarCondenseView()
    case "Toolbar Playground":    ToolbarPlaygroundView()
    case "Safe Areas":             SafeAreasView()
    case "Permission Requests":        PermissionRequestView()
    case "Permission Denied Recovery": PermissionDeniedRecoveryView()
    case "Push Notifications":         PushPermissionView()
    case "Camera":                     CameraConfigListView()
    case "Photo Picker":               PhotoPickerView()
    case "Photo Library Patterns":     PhotoLibraryPatternsView()
    case "Audio Recording":            AudioRecordingView()
    case "Waveform Visualization":     AudioWaveformView()
    case "Playback UI Patterns":       AudioPlaybackPatternsView()
    case "Map Basics":                 MapBasicsView()
    case "Map Annotations":            MapAnnotationsView()
    case "Map Overlays":               MapOverlaysView()
    case "Tap & Long Press":       TapLongPressView()
    case "Swipe & Drag":           SwipeDragView()
    case "Pinch & Zoom":           PinchZoomView()
    case "Rotation":               GestureRotationView()
    case "Transitions":            TransitionsView()
    case "Keyframe Animations":    KeyframeAnimationsView()
    case "Keyframe Studio":        KeyframeStudioView()
    case "Phase Animations":       PhaseAnimationsView()
    case "Symbol Effects":         SymbolEffectsView()
    case "Symbol Playground":      SymbolPlaygroundView()
    case "Matched Geometry":       MatchedGeometryView()
    case "Content Transition":     ContentTransitionView()
    case "VoiceOver Labels":       VoiceOverLabelsView()
    case "Dynamic Type":           DynamicTypeExploreView()
    case "Reduce Motion":          ReduceMotionView()
    case "High Contrast":          HighContrastView()
    case "Live Activity Anatomy":  LiveActivityAnatomyView()
    case "Share Sheet":            ShareSheetView()
    case "Face ID / Touch ID":     FaceIDView()
    case "Clipboard":              ClipboardView()
    case "Quick Look":             QuickLookView()
    case "Document Picker":        DocumentPickerView()
    case "Streaming Text":             StreamingTextView()
    case "Writing Tools Integration":  WritingToolsView()
    case "Image Generation":           ImageGenerationView()
    case "Prompt Input Patterns":      PromptInputView()
    case "Live Token Highlighting":    TokenHighlightingView()
    case "Inline Text Attachments":    InlineAttachmentsView()
    case "Text Wrap & Exclusion":      TextWrapExclusionView()
    case "Text Effects":               TextEffectsView()
    case "Custom Haptics":             CustomHapticsView()
    case "Haptic Studio":              HapticStudioView()
    case "Accelerometer & Gyroscope":  AccelerometerView()
    case "Barometer":                  BarometerView()
    case "Proximity & Ambient Light":  ProximityLightView()
    case "Battery State":              BatteryStateView()
    default:                       SheetsModalsView()
    }
}

func componentDestination(for entry: AppEntry) -> some View {
    appDestination(for: entry)
}
